on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Build and upload binaries
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
        include:
          - goos: darwin
            os: macos-latest
            cgo: 1
          - goos: linux
            os: ubuntu-latest
          - goos: windows
            os: ubuntu-latest
          
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.34
      env:
        CGO_ENABLED: ${{ matrix.cgo }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        md5sum: false
        compress_assets: false
